#ifndef LIBBACAEXCEL_GLOBAL_H
#define LIBBACAEXCEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBBACAEXCEL_LIBRARY)
#  define LIBBACAEXCELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBBACAEXCELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBBACAEXCEL_GLOBAL_H
